import { Component } from '@angular/core';
import { MatDialog } from '@angular/material/dialog';
import { AuthService } from 'src/app/auth/auth.service';
import { CreateAdvertisementDialogComponent } from 'src/app/dialogs/create-advertisement-dialog/create-advertisement-dialog.component';
import { Tile } from 'src/app/models/Tile';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent {
  tiles: Tile[] = [
    {text: 'One', cols: 3, rows: 1, color: 'lightblue'},
    {text: 'Two', cols: 1, rows: 2, color: 'lightgreen'},
    {text: 'Three', cols: 1, rows: 1, color: 'lightpink'},
    {text: 'Four', cols: 2, rows: 1, color: '#DDBDF1'},
  ];
  advertisements: any[] = [
    {
      "id": "3b8835c7-1faa-41bb-9d04-e099660b4b2f",
      "title": "Mercedes-Benz E-Class",
      "subTitle": "Elegant design, luxurious interior",
      "description": "The Mercedes-Benz E-Class boasts an elegant design and a luxurious interior. It offers a smooth ride and cutting-edge technology.",
      "price": 70000,
      "moderatorOverviewStatus": "Accepted",
      "type": "Passenger",
      "make": "Mercedes-Benz",
      "model": "E-Class",
      "bodyType": "Sedan",
      "engineCapacity": 2500,
      "serialNumber": "MBE1234567890",
      "fuelConsumption": 8.2,
      "country": "Germany",
      "city": "Stuttgart",
      "address": "789 Pine Avenue",
      "mileage": 18000,
      "manufactureCountry": "Germany",
      "manufactureDate": "2023-08-20T00:00:00Z",
      "isElectric": false,
      "isNew": false,
      "isUsed": true,
      "isVerified": true,
      "images": [
      ],
      "creatorEmail": "admin@admin.com",
      "creatorFirstName": "Admin",
      "creatorLastName": "Admin",
      "createdAt": "2023-08-20T00:00:00Z",
    },
    {
      "id": "e1d0b7a7-4857-4c6e-abc2-4f51c5f0461d",
      "title": "Toyota Camry LE",
      "subTitle": "2022 Model",
      "description": "A reliable sedan with excellent fuel efficiency and modern features.",
      "price": 25000,
      "moderatorOverviewStatus": "Accepted",
      "type": "Passenger",
      "make": "Toyota",
      "model": "Camry",
      "bodyType": "Sedan",
      "engineCapacity": 2500,
      "serialNumber": "XYZ123456789",
      "fuelConsumption": 30,
      "country": "United States",
      "city": "New York",
      "address": "123 Main Street",
      "mileage": 15000,
      "manufactureCountry": "Japan",
      "manufactureDate": "2022-01-15T10:05:00Z",
      "isElectric": false,
      "isNew": false,
      "isUsed": true,
      "isVerified": true,
      "images": [
      ],
      "creatorEmail": "admin@admin.com",
      "creatorFirstName": "Admin",
      "creatorLastName": "Admin",
      "createdAt": "2023-08-20T00:00:00Z",
    },
    {
      "id": "3b8835c7-1faa-41bb-9d04-e099660b4b2f",
      "title": "Mercedes-Benz E-Class",
      "subTitle": "Elegant design, luxurious interior",
      "description": "The Mercedes-Benz E-Class boasts an elegant design and a luxurious interior. It offers a smooth ride and cutting-edge technology.",
      "price": 70000,
      "moderatorOverviewStatus": "Accepted",
      "type": "Passenger",
      "make": "Mercedes-Benz",
      "model": "E-Class",
      "bodyType": "Sedan",
      "engineCapacity": 2500,
      "serialNumber": "MBE1234567890",
      "fuelConsumption": 8.2,
      "country": "Germany",
      "city": "Stuttgart",
      "address": "789 Pine Avenue",
      "mileage": 18000,
      "manufactureCountry": "Germany",
      "manufactureDate": "2023-08-20T00:00:00Z",
      "isElectric": false,
      "isNew": false,
      "isUsed": true,
      "isVerified": true,
      "images": [
      ],
      "creatorEmail": "admin@admin.com",
      "creatorFirstName": "Admin",
      "creatorLastName": "Admin",
      "createdAt": "2023-08-20T00:00:00Z",
    },
    {
      "id": "e1d0b7a7-4857-4c6e-abc2-4f51c5f0461d",
      "title": "Toyota Camry LE",
      "subTitle": "2022 Model",
      "description": "A reliable sedan with excellent fuel efficiency and modern features.",
      "price": 25000,
      "moderatorOverviewStatus": "Accepted",
      "type": "Passenger",
      "make": "Toyota",
      "model": "Camry",
      "bodyType": "Sedan",
      "engineCapacity": 2500,
      "serialNumber": "XYZ123456789",
      "fuelConsumption": 30,
      "country": "United States",
      "city": "New York",
      "address": "123 Main Street",
      "mileage": 15000,
      "manufactureCountry": "Japan",
      "manufactureDate": "2022-01-15T10:05:00Z",
      "isElectric": false,
      "isNew": false,
      "isUsed": true,
      "isVerified": true,
      "images": [
      ],
      "creatorEmail": "admin@admin.com",
      "creatorFirstName": "Admin",
      "creatorLastName": "Admin",
      "createdAt": "2023-08-20T00:00:00Z",
    },
    {
      "id": "3b8835c7-1faa-41bb-9d04-e099660b4b2f",
      "title": "Mercedes-Benz E-Class",
      "subTitle": "Elegant design, luxurious interior",
      "description": "The Mercedes-Benz E-Class boasts an elegant design and a luxurious interior. It offers a smooth ride and cutting-edge technology.",
      "price": 70000,
      "moderatorOverviewStatus": "Accepted",
      "type": "Passenger",
      "make": "Mercedes-Benz",
      "model": "E-Class",
      "bodyType": "Sedan",
      "engineCapacity": 2500,
      "serialNumber": "MBE1234567890",
      "fuelConsumption": 8.2,
      "country": "Germany",
      "city": "Stuttgart",
      "address": "789 Pine Avenue",
      "mileage": 18000,
      "manufactureCountry": "Germany",
      "manufactureDate": "2023-08-20T00:00:00Z",
      "isElectric": false,
      "isNew": false,
      "isUsed": true,
      "isVerified": true,
      "images": [
      ],
      "creatorEmail": "admin@admin.com",
      "creatorFirstName": "Admin",
      "creatorLastName": "Admin",
      "createdAt": "2023-08-20T00:00:00Z",
    },
    {
      "id": "e1d0b7a7-4857-4c6e-abc2-4f51c5f0461d",
      "title": "Toyota Camry LE",
      "subTitle": "2022 Model",
      "description": "A reliable sedan with excellent fuel efficiency and modern features.",
      "price": 25000,
      "moderatorOverviewStatus": "Accepted",
      "type": "Passenger",
      "make": "Toyota",
      "model": "Camry",
      "bodyType": "Sedan",
      "engineCapacity": 2500,
      "serialNumber": "XYZ123456789",
      "fuelConsumption": 30,
      "country": "United States",
      "city": "New York",
      "address": "123 Main Street",
      "mileage": 15000,
      "manufactureCountry": "Japan",
      "manufactureDate": "2022-01-15T10:05:00Z",
      "isElectric": false,
      "isNew": false,
      "isUsed": true,
      "isVerified": true,
      "images": [
      ],
      "creatorEmail": "admin@admin.com",
      "creatorFirstName": "Admin",
      "creatorLastName": "Admin",
      "createdAt": "2023-08-20T00:00:00Z",
    },
    {
      "id": "3b8835c7-1faa-41bb-9d04-e099660b4b2f",
      "title": "Mercedes-Benz E-Class",
      "subTitle": "Elegant design, luxurious interior",
      "description": "The Mercedes-Benz E-Class boasts an elegant design and a luxurious interior. It offers a smooth ride and cutting-edge technology.",
      "price": 70000,
      "moderatorOverviewStatus": "Accepted",
      "type": "Passenger",
      "make": "Mercedes-Benz",
      "model": "E-Class",
      "bodyType": "Sedan",
      "engineCapacity": 2500,
      "serialNumber": "MBE1234567890",
      "fuelConsumption": 8.2,
      "country": "Germany",
      "city": "Stuttgart",
      "address": "789 Pine Avenue",
      "mileage": 18000,
      "manufactureCountry": "Germany",
      "manufactureDate": "2023-08-20T00:00:00Z",
      "isElectric": false,
      "isNew": false,
      "isUsed": true,
      "isVerified": true,
      "images": [
      ],
      "creatorEmail": "admin@admin.com",
      "creatorFirstName": "Admin",
      "creatorLastName": "Admin",
      "createdAt": "2023-08-20T00:00:00Z",
    },
    {
      "id": "e1d0b7a7-4857-4c6e-abc2-4f51c5f0461d",
      "title": "Toyota Camry LE",
      "subTitle": "2022 Model",
      "description": "A reliable sedan with excellent fuel efficiency and modern features.",
      "price": 25000,
      "moderatorOverviewStatus": "Accepted",
      "type": "Passenger",
      "make": "Toyota",
      "model": "Camry",
      "bodyType": "Sedan",
      "engineCapacity": 2500,
      "serialNumber": "XYZ123456789",
      "fuelConsumption": 30,
      "country": "United States",
      "city": "New York",
      "address": "123 Main Street",
      "mileage": 15000,
      "manufactureCountry": "Japan",
      "manufactureDate": "2022-01-15T10:05:00Z",
      "isElectric": false,
      "isNew": false,
      "isUsed": true,
      "isVerified": true,
      "images": [
      ],
      "creatorEmail": "admin@admin.com",
      "creatorFirstName": "Admin",
      "creatorLastName": "Admin",
      "createdAt": "2023-08-20T00:00:00Z",
    }
  ];

  constructor(public auth: AuthService, private dialog: MatDialog) {

  }

  openCreateAdvertisementDialog() {
    this.dialog.open(CreateAdvertisementDialogComponent, {
      disableClose: true
    });
  }
}
